const translations = {
  "en" : "HELLO",
  "en-US" : "HELLO",
  "en-GB" : "Hello",
  "fr-FR" : "Bonjour",
  "es-ES" : "Hola",
  "it" : "Ciao",
  "Portugese" : "Olá",
  "mi" : "Kia Ora",
  "Australian" : "G'day",
  "el" : "Geia (γεια)",
  "sr" : "Zdravo",
  "hr" : "Zdravo",
  "ru" : "Privet",
  "Mandarin" : "Nǐ hǎo",
  "Cantonese" : "Nǐ hǎo",
  "hi" : "Namaste",
  "ja" : "Kon’nichiwa",
  "tr" : "Merhaba",
  "ko" : "Anyeong Haseyo",
  "sk" : "Ahoj",
  "de" : "Guten tag",
  "nl" : "Hallo",
  "pl" : "Cześć",
  "th" : "S̄wạs̄dī",
  "hu" : "Szia",
  "cs" : "Ahoj",
  "bn" : "Hyālō",
  "ur" : "Assalam u Alaikum",
  "fa" : "Salām",
  "uk" : "Dobryj Den",
  "sv" : "Hallå",
  "af" : "Hallo",
  "ro" : "Bunâ",
  "he" : "Shalom",
  "hy" : "Barev",
  "ar" : "Marhabaan",
  "pa" : "Sata Srī Akāla",
  "Javanese" : "halo",
  "ms" : "Selamat Pagi",
  "vi" : "Xin Chào",
  "eu" : "Kaixo",
  "Bavarian" : "Servus",
  "Tagalog" : "Kamusta",
  "sw" : "Jambo",
  "Uzbek" : "Salom",
  "az" : "Salam",
  "Kurdish" : "Slav",
  "ne" : "Namaste",
  "ht" :"reole = Bonjou",
  "be" : "Dobry Dzień",
  "Chichewa" : "Moni",
  "fj" : "Bula",
  "Hawaiian" : "Aloha",
  "Samoan" : "ālofa",
  "Tongan" : "Mālō e lelei",
  "ji" : "A Gutn Tog",
  "cy" : "S’mae",
  "no" : "Hei",
  "lt" : "Sveiki",
  "lv" : "Sveika (male) Sveiks (female)",
  "is" : "Halló",
  "Scottish" :"aelic = Halò",
  "ga" : "Dia Duit",
  "et" : "Tere",
  "bs" : "Zdravo",
  "Tibetan" : "Tashi Delek",
  "Lao" : "Sabaidee",
  "ka" : "Gamarjoba",
  "Sesotho" : "Dumela",
  "eo" : "Saluton",
  "mt" : "Bongu",
  "Bahaman" : "Hello",
  "Igbo" : "Nde-ewo",
  "lb" : "oïen",
  "nv" : "Ya’at’eeh",
  "Swiss German" : "Grüezi",
  "Tahitian" : "Ia Orana",
  "sq" : "Përshëndetje",
  "ca" : "Hola",
  "Galician" : "Ola",
  "Mongolian" : "Sain uu",
  "Wolof" : "Salaam Aleekum",
  "Wu (Shanghainese)" : "Nóng gō",
  "ta" : "Vanakkam",
  "Pashto" :"alam",
  "kn" : "Namaskāra",
  "Hausa" : "Sannu",
  "my" : "Mingalaba",
  "Amharic" : "Selam",
  "br" : "Demat",
  "om" : "Akkam",
  "Manipuri" : "Khurumjari",
  "Cebuano" : "Kumusta",
  "Malagasy" : "Salama",
  "Santali" : "Henda ho",
  "km" : "Choum Reap Sor",
  "Sinhalese" : "Ayubowan",
  "Somali" : "Salam Alaykum",
  "Taiwanese" :"okkien = Li-hó",
  "tn" : "Dumela",
  "qu" : "Allianchu ",
  "xh" : "Molweni",
}

export default translations;
