(() => {
  // source/js/languages.js
  var translations = {
    "en": "HELLO",
    "en-US": "HELLO",
    "en-GB": "Hello",
    "fr-FR": "Bonjour",
    "es-ES": "Hola",
    "it": "Ciao",
    "Portugese": "Ol\xE1",
    "mi": "Kia Ora",
    "Australian": "G'day",
    "el": "Geia (\u03B3\u03B5\u03B9\u03B1)",
    "sr": "Zdravo",
    "hr": "Zdravo",
    "ru": "Privet",
    "Mandarin": "N\u01D0 h\u01CEo",
    "Cantonese": "N\u01D0 h\u01CEo",
    "hi": "Namaste",
    "ja": "Kon\u2019nichiwa",
    "tr": "Merhaba",
    "ko": "Anyeong Haseyo",
    "sk": "Ahoj",
    "de": "Guten tag",
    "nl": "Hallo",
    "pl": "Cze\u015B\u0107",
    "th": "S\u0304w\u1EA1s\u0304d\u012B",
    "hu": "Szia",
    "cs": "Ahoj",
    "bn": "Hy\u0101l\u014D",
    "ur": "Assalam u Alaikum",
    "fa": "Sal\u0101m",
    "uk": "Dobryj Den",
    "sv": "Hall\xE5",
    "af": "Hallo",
    "ro": "Bun\xE2",
    "he": "Shalom",
    "hy": "Barev",
    "ar": "Marhabaan",
    "pa": "Sata Sr\u012B Ak\u0101la",
    "Javanese": "halo",
    "ms": "Selamat Pagi",
    "vi": "Xin Ch\xE0o",
    "eu": "Kaixo",
    "Bavarian": "Servus",
    "Tagalog": "Kamusta",
    "sw": "Jambo",
    "Uzbek": "Salom",
    "az": "Salam",
    "Kurdish": "Slav",
    "ne": "Namaste",
    "ht": "reole = Bonjou",
    "be": "Dobry Dzie\u0144",
    "Chichewa": "Moni",
    "fj": "Bula",
    "Hawaiian": "Aloha",
    "Samoan": "\u0101lofa",
    "Tongan": "M\u0101l\u014D e lelei",
    "ji": "A Gutn Tog",
    "cy": "S\u2019mae",
    "no": "Hei",
    "lt": "Sveiki",
    "lv": "Sveika (male) Sveiks (female)",
    "is": "Hall\xF3",
    "Scottish": "aelic = Hal\xF2",
    "ga": "Dia Duit",
    "et": "Tere",
    "bs": "Zdravo",
    "Tibetan": "Tashi Delek",
    "Lao": "Sabaidee",
    "ka": "Gamarjoba",
    "Sesotho": "Dumela",
    "eo": "Saluton",
    "mt": "Bongu",
    "Bahaman": "Hello",
    "Igbo": "Nde-ewo",
    "lb": "o\xEFen",
    "nv": "Ya\u2019at\u2019eeh",
    "Swiss German": "Gr\xFCezi",
    "Tahitian": "Ia Orana",
    "sq": "P\xEBrsh\xEBndetje",
    "ca": "Hola",
    "Galician": "Ola",
    "Mongolian": "Sain uu",
    "Wolof": "Salaam Aleekum",
    "Wu (Shanghainese)": "N\xF3ng g\u014D",
    "ta": "Vanakkam",
    "Pashto": "alam",
    "kn": "Namask\u0101ra",
    "Hausa": "Sannu",
    "my": "Mingalaba",
    "Amharic": "Selam",
    "br": "Demat",
    "om": "Akkam",
    "Manipuri": "Khurumjari",
    "Cebuano": "Kumusta",
    "Malagasy": "Salama",
    "Santali": "Henda ho",
    "km": "Choum Reap Sor",
    "Sinhalese": "Ayubowan",
    "Somali": "Salam Alaykum",
    "Taiwanese": "okkien = Li-h\xF3",
    "tn": "Dumela",
    "qu": "Allianchu ",
    "xh": "Molweni"
  };
  var languages_default = translations;

  // source/js/index.js
  var language = navigator.language || navigator.userLanguage;
  if (languages_default[language]) {
    app.innerText = languages_default[language];
  } else {
    app.innerText = languages_default["en"];
  }
})();
